USER_LOCAL=/usr/local/bin:/usr/local/sbin/
RVM_BIN=$HOME/.rvm/bin/

PATH=$PATH:$USER_LOCAL:$RVM_BIN # Add RVM to PATH for scripting

if [ -f ~/.bash/bash_aliases ]; then
   source ~/.bash/bash_aliases
fi

#if [ -f ~/.osx ]; then
#   source ~/.osx
#fi

if [ -f ~/.bash/bash_extra ]; then
   source ~/.bash/bash_extra
fi

