PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

if [ -f ~/.bash/bash_aliases ]; then
   source ~/.bash/bash_aliases
fi

#if [ -f ~/.osx ]; then
#   source ~/.osx
#fi

if [ -f ~/.bash/bash_extra ]; then
   source ~/.bash/bash_extra
fi
